### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '~/Projects/kitchenstore/vendor/cache/gems/minite...

### ISSUE THREAD

**Issue by sunil-ghorpade** [zakwanhaj/auto-encoding-for-ruby#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [auto-encoding-for-ruby](https://github.com/zakwanhaj/auto-encoding-for-ruby) package, v1.0.4
### Stack Trace

Uncaught Error: EACCES: permission denied, open '/home/sunil/Projects/kitchenstore/vendor/cache/gems/minitest-5.9.0/lib/hoe/minitest.rb'

```
At fs.js:584

Error: EACCES: permission denied, open '/home/sunil/Projects/kitchenstore/vendor/cache/gems/minitest-5.9.0/lib/hoe/minitest.rb'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at ProjectEditor.module.exports.ProjectEditor.insertText (/home/sunil/.atom/packages/auto-encoding-for-ruby/lib/project-editor.coffee:38:15)
    at /home/sunil/.atom/packages/auto-encoding-for-ruby/lib/project-editor.coffee:19:20
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
  3x -8:04.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -8:03.0 core:move-left (atom-text-editor.editor.is-focused)
  6x -8:01.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:53.8.0 core:move-down (atom-text-editor.editor.is-focused)
  6x -7:49.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:43.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:36.6.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:35.2.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -7:06.6.0 execute-as-ruby:execute (atom-text-editor.editor.is-focused)
  2x -4:07.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:54 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:48.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:37.6.0 execute-as-ruby:execute (atom-text-editor.editor.is-focused)
     -3:09.0 grammar-selector:show (atom-text-editor.editor)
     -2:54.9.0 application:add-project-folder (a.inline-block)
     -0:03.5.0 auto-encoding-for-ruby:add-encoding-directory (span.name.icon.icon-file-directory)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
auto-encoding-for-ruby, v1.0.4 (active)
autocomplete-ruby, v0.1.0 (active)
execute-as-ruby, v0.2.1 (active)
rails-i18n-autocomplete, v0.4.0 (active)
rails-latest-migration, v1.1.6 (inactive)
rails-snippets, v2.8.0 (inactive)
rails-transporter, v1.6.5 (inactive)
rubocop-auto-correct, v1.5.1 (inactive)
ruby-block, v0.3.5 (active)
ruby-define-method, v0.2.2 (active)
ruby-test, v0.9.17 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by zakwanhaj** [comment]
I think the error is pretty obvious. You tried to use auto-encoding-for-ruby on a file that your user didn't have read permissions for, use chmod to fix the permissions and then retry.

**Comment by sunil-ghorpade** [comment]
Thanks a lot. I have just started learning. Thats why

Regards,

Sunil Ghorpade
+91-9922298533

**Comment by zakwanhaj** [comment]
No worries..
